version: "3.8"

services:
  app:
    build: .
    container_name: yii2-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    environment:
      - APP_ENV=local
    command: ["php-fpm"]
